import "./globals.css";

import ContactSection from "@/components/contact-section";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import React from "react";
import SplashCursor from "@/components/reactbits/SplashCursor/SplashCursor";
import StickyHeader from "@/components/sticky-header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link
					href="https://api.fontshare.com/v2/css?f[]=clash-display@400,500,600,700&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body
				className={`${inter.variable} antialiased bg-background text-foreground`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem={false}
					disableTransitionOnChange
				>
					<TooltipProvider>
						<Toaster />
						<StickyHeader />
						{children}
						<ContactSection />
						<Footer />
						<SplashCursor />
					</TooltipProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
